openapi: 3.0.2
info:
  title: Register Services API
  description: API used to register user for FindMySalon Services
  version: Initial
servers:
  - url: http://localhost:8080
    description: local
  - url: https://authorization-spj.herokuapp.com
    description: heroku
tags:
  - name: registerUser
  - name: registerClient
paths:
  /client/register:
    post:
      operationId: registerClient
      tags:
        - registerClient
      summary: Register a client
      description: Register a client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterClientRequest'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterClientResponse'
  /oauth/no-ops:
    get:
      operationId: getAccessToken
      tags:
        - customOAuth
      summary: Get access for a client based on authorization code
      description: Get access for a client based on authorization code
      parameters:
        - in: header
          name: authorization
          required: false
          schema:
            type: string
        - in: query
          name: code
          required: true
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
components:
  schemas:
    RegisterClientRequest:
      type: object
      properties:
        clientName:
          type: string
        clientPassword:
          type: string
        redirectUri:
          type: string
      required:
        - clientName
        - clientPassword
        - redirectUri
    RegisterClientResponse:
      type: object
      properties:
        clientName:
          type: string
        message:
          type: string
    AuthTokenResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        refresh_token:
          type: string
        email:
          type: string